@urlDev=http://localhost:3000/v1/api
@contentType=application/json
POST  {{urlDev}}/shop/signup
content-type: {{contentType}}

{
    "name": "shop Test",
    "email": "shoptest08@gmail.com",
    "password": "abc123"
}